pipeline {
    agent any

    tools {
        python 'Python3'   // Make sure Python3 is configured under Manage Jenkins → Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-credentials',
                    url: 'https://github.com/SPaci20/alx-backend-python.git',
                    branch: 'main'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install --upgrade pip pytest'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'  // publish test results in Jenkins
                }
            }
        }
    }

    triggers {
        // Manual trigger only
    }
}
