version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQLUSER: ${MYSQLUSER}
      MYSQLDB: ${MYSQLDB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQLUSER: ${MYSQLUSER}
      MYSQLDB: ${MYSQLDB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQLHOST: db
    depends_on:
      - db

volumes:
  db_data:
